### ISSUE TITLE
Create manifest.yml

### ISSUE THREAD

**Issue by eloo** [pivotalservices/ya-cf-app-gradle-plugin#11]
Hi,
is it possible to let the plugin create a manifest.yml based on the set properties and the variables passed via CLI?

Thanks

**Comment by bijukunjummen** [comment]
It is possible @Eloo, just curious - how do you plan to use such a feature though. Wouldn't plugin consuming a cf manifest be a more useful feature?

**Comment by bijukunjummen** [comment]
Oh, you can handle multiple environments differently, along these lines:

```cfConfig {
	//CF Details
	ccHost = "api.local.pcfdev.io"
	ccUser = "admin"
	ccPassword = "admin"
}```

You can override the configuration for a different environment by giving a property with `cf` prefix..so for QA say you can call it this way:

`./gradlew cf-push -Pcf.ccHost=newhost -Pcf.ccUser=newUser -Pcf.ccPassword=newpw`.

**Comment by Eloo** [comment]
okay but now i have to enter these every time.. if i could create a manifest it would make some things easier

**Comment by bijukunjummen** [comment]
Sorry @eloo, I am not sure I understand how this will be helpful - the gradle task is expected to be executed via a CI/CD tool like Jenkins and so the override should work there cleanly. I think you may be better of simply using the command line client (cf-cli) and the yaml based manifest directly.

**Comment by eloo** [comment]
@bijukunjummen yes i want to use the cf-cli with the manifest.. but i want to create the manifest with this plugin if possible

**Comment by gmcouto** [comment]
I would add a +1 to be able to load defaults from manifest.yml also. But I think this issue is for something completely different, @cah-briangantzler

**Comment by bijukunjummen** [comment]
closed via https://github.com/pivotalservices/ya-cf-app-gradle-plugin/pull/27
