### ISSUE TITLE
How to use the plugin behind proxy

### ISSUE THREAD

**Issue by RyanKys** [pivotalservices/ya-cf-app-gradle-plugin#15]
Hi, may I ask how to use this plug-in behind proxy? I tried setting environment variables "set HTTP_PROXY / HTTPS_PROXY" and define "systemProp.https.proxyHost/proxyPort", but no luck...

**Comment by bijukunjummen** [comment]
saw some discussion here @RyanKys - https://github.com/cloudfoundry/cf-java-client/issues/479. PR welcome if you can figure it out.

**Comment by andreas-schilling** [comment]
I added a PR, see https://github.com/pivotalservices/ya-cf-app-gradle-plugin/pull/18

**Comment by bijukunjummen** [comment]
You can use the feature with this version of the plugin:

```

buildscript {
	ext {
		cfAppVersion = '2.2.0-rc.1'
	}
	repositories {
		mavenCentral()
		maven { url "https://oss.sonatype.org/content/repositories/releases" }
		maven { url "https://repo.spring.io/release" }
	}
	dependencies {
		classpath("com.github.pivotalservices:ya-cf-app-gradle-plugin:${cfAppVersion}")
	}
}

apply plugin: 'cf-app'

```

Details of how to add the proxy settings are in the README
