### ISSUE TITLE
Adding functionality for service brokers

### ISSUE THREAD

**Issue by michaellihs** [pivotalservices/ya-cf-app-gradle-plugin#17]
Hi @bijukunjummen 

we are building a service broker for CF with Gradle and would like to cover the registration of the app as a service broker with your Gradle plugin. So question is: if we implement this as a new feature for your plugin, would you accept a pull request for this or do you not see this functionality in the scope of your tool.

Thanks for an answer, regards

Michael

**Comment by bijukunjummen** [comment]
Hey @michaellihs , awesome to hear that you are using the plugin.  Regarding your question, you are looking at the equivalent of `cf create-service-broker` functionality in the plugin right, I feel that the plugin may not be the right place for this functionality as it is focused on application concerns (deploying, start, stop, map-route etc) and registering an endpoint as a service broker feels orthogonal.

**Comment by michaellihs** [comment]
@bijukunjummen thanks for the fast response, so will most likely implement another plugin to do this :)
