### ISSUE TITLE
How are routes specified

### ISSUE THREAD

**Issue by cah-briangantzler** [pivotalservices/ya-cf-app-gradle-plugin#26]
I dont see how routes are specified. Im guessing appname + domain.

Would like to specify the route directly so it could differ (other than the app name),

Also need a path as in appname.domain/api for example. 

Possibly multiple routes

**Comment by gmcouto** [comment]
There is a host property to allow it to be different than app name.

But I would vote +1 to allow multiple routes with multiple domains and app names.

**Comment by bijukunjummen** [comment]
PR's welcome @gmcouto :-)

**Comment by bijukunjummen** [comment]
Closed via https://github.com/pivotalservices/ya-cf-app-gradle-plugin/pull/27
